export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const GET_ALL_STORE = "GET_ALL_STORE";
export const SAVE_NEW_STORE_LOADING = "SAVE_NEW_STORE ";
export const ADD_NEW_STORE_FAILED = "ADD_NEW_STORE_FAILED";
export const ADD_NEW_STORE_SUCCESS = "ADD_NEW_STORE_SUCCES";
export const DELETE_STORE = "DELETE_STORE";
export const DELETE_STORE_FAILED = "DELETE_STORE_FAILED";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";


export const ADD_NEW_ORDER_LOADING = "ADD_NEW_ORDER_LOADING ";
export const ADD_NEW_ORDER_FAILED = "ADD_NEW_ORDER_FAILED";
export const ADD_NEW_ORDER_SUCCESS = "ADD_NEW_ORDER_SUCCESS";


export const GET_ALL_STATUS = "GET_ALL_STATUS";
export const  SAVE_NEW_STATUS= " SAVE_NEW_STATUS";
export const SAVE_STATUS_FAILED = "SAVE_STATUS_FAILED";
export const SAVE_STATUS_SUCCESS = "SAVE_STATUS_SUCCES";





export const CREATING_DISPATCH = "CREATING_DISPATCH";
export const CREATING_DISPATCH_SUCCESS = "CREATING_DISPATCH_SUCCESS";
export const CREATING_DISPATCH_FAILURE = "CREATING_DISPATCH_FAILURE";
// export const DELETE_STORE = "DELETE_STORE";
// export const DELETE_STORE_FAILED = "DELETE_STORE_FAILED";
// export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";

export const CREATING_USER = "CREATING_USER";
export const CREATING_USER_SUCCESS ="CREATING_USER_SUCCESS";
export const CREATING_USER_FAILURE ="CREATING_USER_FAILURE";




